// REPOSITORIES/SERVICES
export const JWT_SERVICE = Symbol('JWT_SERVICE');

// USECASES
export const CREATE_TOKEN_RESET_PASSWORD_USE_CASE = Symbol(
  'CREATE_TOKEN_RESET_PASSWORD_USE_CASE',
);
export const RESET_PASSWORD_USE_CASE = Symbol('RESET_PASSWORD_USE_CASE');
export const AUTH_USE_CASE = Symbol('AUTH_USE_CASE');
