// REPOSITORIES/SERVICES
export const EQUIPMENT_CATEGORY_REPOSITORY = Symbol(
  'EQUIPMENT_CATEGORY_REPOSITORY',
);

// USECASES
export const CREATE_EQUIPMENT_CATEGORY_USE_CASE = Symbol(
  'CREATE_EQUIPMENT_CATEGORY_USE_CASE',
);
export const FIND_EQUIPMENT_CATEGORIES_USE_CASE = Symbol(
  'FIND_EQUIPMENT_CATEGORIES_USE_CASE',
);
export const UPDATE_EQUIPMENT_CATEGORY_NAME_USE_CASE = Symbol(
  'UPDATE_EQUIPMENT_CATEGORY_NAME_USE_CASE',
);
