// REPOSITORIES/SERVICES
export const EQUIPMENT_CATEGORY_REPOSITORY = Symbol(
  'EQUIPMENT_CATEGORY_REPOSITORY',
);

// USECASES
export const CREATE_EQUIPMENT_CATEGORY_USE_CASE = Symbol(
  'CREATE_EQUIPMENT_CATEGORY_USE_CASE',
);
